const express = require("express");
const router = express.Router();
const userController = require("../controllers/user.controller");
const asyncHandler = require("../utils/asyncHandler");
router.get("/", asyncHandler(userController.getAll));
router.post("/", asyncHandler(userController.create));
router.get("/:id", asyncHandler(userController.getById));
router.put("/:id", asyncHandler(userController.update));
router.delete("/:id", userController.delete);
module.exports = router;